webtalk_init -webtalk_dir C:/Users/lbarry22/Desktop/MIPS1_ALU/MIPS1_ALU.sim/sim_1/behav/xsim/xsim.dir/sim_alu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 11 22:49:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "afcc4c4b-93f6-453f-b0d3-9ede23d0ae20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e3ad109398c14002ad63d7f5587fc7dd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 s" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.94_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1758994576 -regid "" -xml C:/Users/lbarry22/Desktop/MIPS1_ALU/MIPS1_ALU.sim/sim_1/behav/xsim/xsim.dir/sim_alu_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/lbarry22/Desktop/MIPS1_ALU/MIPS1_ALU.sim/sim_1/behav/xsim/xsim.dir/sim_alu_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/lbarry22/Desktop/MIPS1_ALU/MIPS1_ALU.sim/sim_1/behav/xsim/xsim.dir/sim_alu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
